apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-auth.fullname" . }}
  labels:
    app: {{ include "go-auth.name" . }}
    chart: {{ include "go-auth.chart" . }}
spec:
  type: {{ .Values.goAuth.service.type }}
  ports:
    - port: {{ .Values.goAuth.service.port }}
      targetPort: {{ .Values.goAuth.service.port }} 
  selector:
    app: {{ include "go-auth.name" . }}
    release: {{ .Release.Name }}
