name: Build Image & Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.3.8
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "go-auth"
          IMAGE_TAG: "latest"
        run: |
          docker build -t go-auth .
          docker tag go-auth:latest public.ecr.aws/j6h8q3k6/go-auth:latest
          docker push public.ecr.aws/j6h8q3k6/go-auth:latest
          echo "::set-output name=image::public.ecr.aws/j6h8q3k6/go-auth:latest"
        
        # we need now to create deployment.yaml and then we use new image in it