name: Build Image & Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Scan current project
        id: scan
        uses: anchore/scan-action@v3.3.8
        with:
          path: "./"
          fail-build: true
          acs-report-enable: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and push the image to ECR
        env:
          ECR_REGISTRY: '${{ secrets.ECR_REGISTRY }}'
          IMAGE_NAME: "go-auth"
          IMAGE_TAG: "latest"
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/$ECR_REGISTRY
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:$IMAGE_TAG public.ecr.aws/$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker push public.ecr.aws/$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG        

      - uses: WyriHaximus/github-action-helm3@v2.0
      - name: Deploy App
        with:
          exec: helm upgrade -i go-auth ./.helm -n go-auth
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy Prometheus
        with:
          exec: helm upgrade -i -n go-auth prometheus prometheus-community/prometheus -f ./.helm/charts/monitoring/values.yaml
          kubeconfig: '${{ secrets.KUBECONFIG }}'